-- api_keys: an owner may UPDATE their own key row (BEL-273, PR #42)
--
-- Refs BEL-273, BEL-282
--
-- WHY THIS FILE EXISTS
--
-- `20261004123918_create_belmont_news_schema.sql:230-246` creates three policies on api_keys:
-- owner_read (SELECT), owner_insert (INSERT) and owner_delete (DELETE). There is no
-- owner_update. RLS is enabled on the table at line 230.
--
-- With RLS enabled and no UPDATE policy, PostgREST matches zero rows on every UPDATE
-- issued as `authenticated`. It returns 200 with an empty body, not an error, because
-- nothing failed -- there was simply no policy permitting the row. A client that reads
-- only `error` sees success.
--
-- Two paths in the panel are already UPDATE and are therefore already no-ops:
--
--   src/pages/DashboardPage.tsx:207-222  handleRerollKey
--     update({ key_hash: rawKey, key_prefix: prefix }).eq('id', keyId)
--
-- That is the live reroll button. On a database built from the migrations in this
-- repository it reports success, the panel then shows the newly generated raw key
-- exactly once, and the row on the server is unchanged. The desk is handed a credential
-- that was never issued, and the previous credential keeps working. The old key is
-- neither replaced nor invalidated.
--
--   src/pages/DashboardPage.tsx:223-231  handleDeleteKey
--     delete().eq('id', keyId)  -- this one has a policy and does work today.
--
-- The revoke-instead-of-delete change in the panel (PR C, BEL-282) turns deletion into
-- `update({ revoked_at })`. That is an UPDATE, so it inherits this same gap. Without this
-- file, PR C ships a revoke button that reports success and leaves the key live -- the
-- precise failure the change exists to remove, arrived at from the other direction.
--
-- Ordering. This file lands after 20261005290000 (PR #40), which is what adds the
-- `revoked_at` column this policy is needed to write. It must land before the panel
-- change that writes `revoked_at` (PR C). It does not depend on the edge function
-- (PR C) or on the byline work on PR #24.
--
-- Version key. This file was 20261005210000 while PR #40's was 20261005200000. PR #40
-- has since renumbered itself to 20261005290000, above every key in flight, which left
-- this file sorting *before* the columns it is sequenced behind. Nothing functional
-- rides on the order -- the only identifier this policy tests is user_id, which the
-- base schema supplies -- but a file whose own header states a dependency should not
-- be numbered against it. Renumbered to 20261005300000 so the ledger reads in the order
-- the comments describe: 290000 digest columns, then 300000 this policy, then 310000
-- the column drop.
--
-- The edge function is unaffected. It authenticates and stamps `last_used_at` through
-- SUPABASE_SERVICE_ROLE_KEY (supabase/functions/api/index.ts:10-13), and service_role
-- bypasses RLS. This file grants nothing to any role; it adds one policy for
-- `authenticated`, scoped to the caller's own rows by the same expression the three
-- existing policies already use.

-- ============================================================
-- SECTION 1. GRANT PRECHECK
--
-- A policy is necessary but not sufficient. An UPDATE also needs the table-level UPDATE
-- privilege for the `authenticated` role, and Postgres evaluates privilege and policy
-- independently: with the privilege but no policy the row is filtered out; with the
-- policy but no privilege the statement is denied.
--
-- The only GRANT or REVOKE anywhere in this repository is on public.comments_public
-- (20261005160000_comments_public_view.sql:102-103), so no column-scoped grant on
-- api_keys is expected. That is an expectation, not a measurement, and it is the same
-- assumption PR #40 declines to act on in its own section 6.
--
-- A table-level grant appears in information_schema.column_privileges expanded to one
-- row per column, so a populated column list here is not by itself evidence of a narrow
-- grant. This block compares table_privileges against column_privileges for the same
-- grantee and privilege, exactly as PR #40 section 6 does, and raises if the answer is
-- not the one this file needs. It reads and never writes.
--
-- If it raises: do not edit this file to add a GRANT. Extend the existing grants in a
-- separate migration and re-run this one, the same rule PR #40 states.
-- ============================================================
DO $$
DECLARE
  has_table_update boolean;
  has_column_update boolean;
  update_columns   text;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM information_schema.table_privileges
    WHERE table_schema = 'public' AND table_name = 'api_keys'
      AND grantee = 'authenticated' AND privilege_type = 'UPDATE'
  ) INTO has_table_update;

  SELECT EXISTS (
    SELECT 1 FROM information_schema.column_privileges
    WHERE table_schema = 'public' AND table_name = 'api_keys'
      AND grantee = 'authenticated' AND privilege_type = 'UPDATE'
  ) INTO has_column_update;

  IF has_column_update AND NOT has_table_update THEN
    SELECT string_agg(column_name, ', ' ORDER BY column_name)
      INTO update_columns
      FROM information_schema.column_privileges
     WHERE table_schema = 'public' AND table_name = 'api_keys'
       AND grantee = 'authenticated' AND privilege_type = 'UPDATE';

    RAISE EXCEPTION
      'authenticated holds a COLUMN-scoped UPDATE on api_keys (%), not a table-level one. '
      'This file adds a policy and cannot widen a grant, so applying it alone will leave '
      'every owner UPDATE denied. Do not apply this file. Add a separate migration '
      'extending the existing UPDATE grant to table level, then re-apply.', update_columns;
  END IF;

  -- The mirror case: no UPDATE privilege at all. That is not this file's business to fix
  -- -- a missing grant is fixable out of band, unlike a narrowed one, which is why the case
  -- above aborts and this one does not. But it ends in the same "looks fixed" state, so it
  -- is reported loudly rather than passed over in silence.
  IF NOT has_table_update THEN
    RAISE WARNING
      'authenticated holds NO table-level UPDATE on api_keys. This migration will add the '
      'policy and report success, and every owner UPDATE will still be refused on privilege '
      'before any policy is consulted. Grant UPDATE on the table before expecting rotation '
      'to work; this file deliberately does not issue that grant.';
  END IF;

  RAISE NOTICE 'api_keys: authenticated holds table-level UPDATE = %, column-scoped UPDATE = %.',
    has_table_update, has_column_update;

  -- Cross-check with the ACL directly. information_schema.table_privileges and
  -- column_privileges report a grant only where the GRANTOR OR the GRANTEE is a role
  -- currently enabled in the session, so a role that is neither sees zero rows and both
  -- EXISTS above return false -- the check then passes vacuously while its NOTICE reads
  -- like a result. has_table_privilege reads the relation's ACL and has no such filter.
  -- Supabase applies migrations as the table owner, so in practice the two agree; this is
  -- here so the vacuous case is visible instead of silent.
  IF NOT has_table_privilege('authenticated', 'public.api_keys', 'UPDATE') THEN
    RAISE WARNING
      'has_table_privilege() disagrees with information_schema above: authenticated cannot '
      'UPDATE api_keys through the ACL either. The information_schema read may have been '
      'vacuous (grantor and grantee both not enabled in this session). Re-check before '
      'relying on either answer.';
  END IF;
END
$$;

-- ============================================================
-- SECTION 2. The policy
--
-- USING and WITH CHECK are both auth.uid() = user_id, matching api_keys_owner_read,
-- _insert and _delete.
--
-- Why both clauses, stated accurately. An earlier draft of this comment claimed that
-- omitting WITH CHECK would let an owner repoint their key row at another user_id.
-- That is not what PostgreSQL does. The CREATE POLICY reference is explicit: for
-- UPDATE, "if only a USING clause is specified, then that clause will be used for
-- both USING and WITH CHECK cases." Omitting the clause here would impose exactly the
-- same restriction. So the clause is NOT load-bearing against that hazard, and this
-- comment does not claim it is.
--
-- It is kept because it makes the policy self-describing at the point of definition
-- rather than relying on the reader knowing the default, and because the precedent on
-- this table already spells it out: comments_owner_update at
-- 20261004123918_create_belmont_news_schema.sql:200-203 is the same verb with the same
-- explicit pair. The other two api_keys policies are not a precedent for it --
-- api_keys_owner_insert carries only WITH CHECK and api_keys_owner_delete only USING --
-- so citing them as "the established shape" would have been wrong.
--
-- The policy does not constrain which columns may be written. RLS cannot do that. The
-- consequence is stated plainly rather than left implied: an owner who can UPDATE their
-- row can write key_hash, and therefore can choose a credential, and the
-- api_keys_fill_key_digest trigger from 20261005290000 recomputes key_digest to match.
-- That is the reroll the panel already offers and the only reason this policy is being
-- added, so it is not new authority -- it is authority the code has always assumed and
-- never had. It is also why the panel must stop selecting key_hash (PR C, BEL-282): with
-- a working UPDATE policy, a browser that can read the column can also overwrite it, so
-- the SELECT exposure and the write capability now compound.
--
-- No grant is added, widened, or narrowed here.
--
-- Dropped before created so a replay does not abort with "policy already exists". Every
-- non-IF-NOT-EXISTS CREATE in this repository is preceded by its drop: see PR #27,
-- weather_admin_delete, and PR #40 section 9.
-- ============================================================
DROP POLICY IF EXISTS "api_keys_owner_update" ON public.api_keys;

CREATE POLICY "api_keys_owner_update"
  ON public.api_keys FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

COMMENT ON POLICY "api_keys_owner_update" ON public.api_keys IS
  'Owner-scoped UPDATE, completing the read/insert/delete set from 20261004123918. Required by handleRerollKey and by the revoked_at write that replaces deletion (BEL-273 PR C). WITH CHECK is explicit for the same restriction USING already gives, per the CREATE POLICY default; it is documentation, not an additional guard. Column scope is not expressible in RLS: an owner may write key_hash, which is the reroll the panel already offers.';

-- ============================================================
-- SECTION 3. Post-check
--
-- Reads the expected state back so the operator is not relying on this file's own
-- success message alone. A policy that exists but does not narrow to the caller is worse
-- than no policy, because it looks fixed.
--
-- What this check does and does not prove, stated precisely. It deparses both clauses and
-- asks whether the text names auth.uid() and user_id. That is a substring test: it passes
-- on `user_id <> auth.uid()` and on `auth.uid() = user_id OR true`, so it proves the two
-- identifiers appear, not that the policy narrows to the caller. It is a cheap guard
-- against the policy having been created with something else in it, and it is not
-- evidence of correctness. The error message says "does not reference", which is the
-- honest description of what it tests.
--
-- Deparse is anchored to a search_path that excludes `auth` and `public`, so a role whose
-- own search_path contains `auth` -- the `authenticator` role does -- gets the same
-- deparsed text as everyone else. Without this, pg_get_expr would print `uid()` instead
-- of `auth.uid()`, the substring test would fail, and this block would RAISE on a
-- correctly migrated database, rolling back the policy it had just verified. That is
-- precisely the outcome this section exists to prevent, so the path is pinned.
-- ============================================================
DO $$
DECLARE
  policy_def       text;
  names_both_ids   boolean;
BEGIN
  PERFORM set_config('search_path', 'pg_catalog', true);

  -- coalesce on the NULL polwithcheck: `x || NULL` is NULL, so a policy present with a
  -- NULL WITH CHECK would otherwise be indistinguishable from a policy that is absent,
  -- and reported as "absent after this migration ran".
  SELECT coalesce(pg_get_expr(pol.polqual, pol.polrelid), '<none>')
         || ' / ' || coalesce(pg_get_expr(pol.polwithcheck, pol.polrelid), '<none>')
    INTO policy_def
    FROM pg_policy pol
   WHERE pol.polrelid = 'public.api_keys'::regclass
     AND pol.polname = 'api_keys_owner_update';

  IF policy_def IS NULL THEN
    RAISE EXCEPTION 'api_keys_owner_update is absent after this migration ran.';
  END IF;

  names_both_ids := policy_def LIKE '%auth.uid()%' AND policy_def LIKE '%user_id%';

  IF NOT names_both_ids THEN
    RAISE EXCEPTION
      'api_keys_owner_update does not reference auth.uid() and user_id in both its USING '
      'and WITH CHECK expressions. It reads: %', policy_def;
  END IF;

  RAISE NOTICE 'api_keys: owner UPDATE policy present and names auth.uid() and user_id. USING/WITH CHECK: %', policy_def;
  RAISE NOTICE 'api_keys: 4 owner policies now exist (SELECT, INSERT, DELETE, UPDATE).';

  -- The policy narrowing is only half the condition. A policy backed by no UPDATE
  -- privilege is refused on privilege before the policy is ever consulted, which is the
  -- same "looks fixed" state this section is about. Read the ACL again here rather than
  -- trusting section 1 to have covered it.
  IF NOT has_table_privilege('authenticated', 'public.api_keys', 'UPDATE') THEN
    RAISE WARNING
      'api_keys_owner_update exists and is owner-scoped, but authenticated still cannot '
      'UPDATE api_keys. The policy will not be consulted. Grant UPDATE on the table; this '
      'file does not, by design.';
  END IF;
END
$$;

-- PostgREST caches the schema and the policy list. Without this reload the panel keeps
-- seeing the pre-migration policy set and the reroll button stays a no-op until the
-- cache expires, which reads as "the migration did not work". Same reason as
-- NOTIFY pgrst, 'reload schema' at the end of both PR #24 migrations.
NOTIFY pgrst, 'reload schema';