-- api_keys: an owner may UPDATE their own key row (BEL-273, PR #41)
--
-- Refs BEL-273, BEL-282
--
-- WHY THIS FILE EXISTS
--
-- `20261004123918_create_belmont_news_schema.sql:230-246` creates three policies on api_keys:
-- owner_read (SELECT), owner_insert (INSERT) and owner_delete (DELETE). There is no
-- owner_update. RLS is enabled on the table at line 230.
--
-- With RLS enabled and no UPDATE policy, PostgREST matches zero rows on every UPDATE
-- issued as `authenticated`. It returns 200 with an empty body, not an error, because
-- nothing failed -- there was simply no policy permitting the row. A client that reads
-- only `error` sees success.
--
-- Two paths in the panel are already UPDATE and are therefore already no-ops:
--
--   src/pages/DashboardPage.tsx:207-222  handleRerollKey
--     update({ key_hash: rawKey, key_prefix: prefix }).eq('id', keyId)
--
-- That is the live reroll button. On a database built from the migrations in this
-- repository it reports success, the panel then shows the newly generated raw key
-- exactly once, and the row on the server is unchanged. The desk is handed a credential
-- that was never issued, and the previous credential keeps working. The old key is
-- neither replaced nor invalidated.
--
--   src/pages/DashboardPage.tsx:223-231  handleDeleteKey
--     delete().eq('id', keyId)  -- this one has a policy and does work today.
--
-- The revoke-instead-of-delete change in the panel (PR C, BEL-282) turns deletion into
-- `update({ revoked_at })`. That is an UPDATE, so it inherits this same gap. Without this
-- file, PR C ships a revoke button that reports success and leaves the key live -- the
-- precise failure the change exists to remove, arrived at from the other direction.
--
-- Ordering. This file lands after 20261005200000 (PR #40), which is what adds the
-- `revoked_at` column this policy is needed to write. It must land before the panel
-- change that writes `revoked_at` (PR C). It does not depend on the edge function
-- (PR C) or on the byline work on PR #24.
--
-- The edge function is unaffected. It authenticates and stamps `last_used_at` through
-- SUPABASE_SERVICE_ROLE_KEY (supabase/functions/api/index.ts:10-13), and service_role
-- bypasses RLS. This file grants nothing to any role; it adds one policy for
-- `authenticated`, scoped to the caller's own rows by the same expression the three
-- existing policies already use.

-- ============================================================
-- SECTION 1. GRANT PRECHECK
--
-- A policy is necessary but not sufficient. An UPDATE also needs the table-level UPDATE
-- privilege for the `authenticated` role, and Postgres evaluates privilege and policy
-- independently: with the privilege but no policy the row is filtered out; with the
-- policy but no privilege the statement is denied.
--
-- The only GRANT or REVOKE anywhere in this repository is on public.comments_public
-- (20261005160000_comments_public_view.sql:102-103), so no column-scoped grant on
-- api_keys is expected. That is an expectation, not a measurement, and it is the same
-- assumption PR #40 declines to act on in its own section 6.
--
-- A table-level grant appears in information_schema.column_privileges expanded to one
-- row per column, so a populated column list here is not by itself evidence of a narrow
-- grant. This block compares table_privileges against column_privileges for the same
-- grantee and privilege, exactly as PR #40 section 6 does, and raises if the answer is
-- not the one this file needs. It reads and never writes.
--
-- If it raises: do not edit this file to add a GRANT. Extend the existing grants in a
-- separate migration and re-run this one, the same rule PR #40 states.
-- ============================================================
DO $$
DECLARE
  has_table_update boolean;
  has_column_update boolean;
  update_columns   text;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM information_schema.table_privileges
    WHERE table_schema = 'public' AND table_name = 'api_keys'
      AND grantee = 'authenticated' AND privilege_type = 'UPDATE'
  ) INTO has_table_update;

  SELECT EXISTS (
    SELECT 1 FROM information_schema.column_privileges
    WHERE table_schema = 'public' AND table_name = 'api_keys'
      AND grantee = 'authenticated' AND privilege_type = 'UPDATE'
  ) INTO has_column_update;

  IF has_column_update AND NOT has_table_update THEN
    SELECT string_agg(column_name, ', ' ORDER BY column_name)
      INTO update_columns
      FROM information_schema.column_privileges
     WHERE table_schema = 'public' AND table_name = 'api_keys'
       AND grantee = 'authenticated' AND privilege_type = 'UPDATE';

    RAISE EXCEPTION
      'authenticated holds a COLUMN-scoped UPDATE on api_keys (%), not a table-level one. '
      'This file adds a policy and cannot widen a grant, so applying it alone will leave '
      'every owner UPDATE denied. Do not apply this file. Add a separate migration '
      'extending the existing UPDATE grant to table level, then re-apply.', update_columns;
  END IF;

  RAISE NOTICE 'api_keys: authenticated holds table-level UPDATE = %, column-scoped UPDATE = %.',
    has_table_update, has_column_update;
END
$$;

-- ============================================================
-- SECTION 2. The policy
--
-- USING and WITH CHECK are both auth.uid() = user_id, matching api_keys_owner_read,
-- _insert and _delete.
--
-- WITH CHECK is not redundant. USING decides which existing rows may be updated; the
-- check decides what the row may become. Without it, an owner could update their own row
-- and set user_id to another profile id, moving the key onto an account they do not
-- control. Every one of the three existing policies that can write carries the same
-- pair, so this is the established shape here rather than a new precaution.
--
-- The policy does not constrain which columns may be written. RLS cannot do that. The
-- consequence is stated plainly rather than left implied: an owner who can UPDATE their
-- row can write key_hash, and therefore can choose a credential, and the
-- api_keys_fill_key_digest trigger from 20261005200000 recomputes key_digest to match.
-- That is the reroll the panel already offers and the only reason this policy is being
-- added, so it is not new authority -- it is authority the code has always assumed and
-- never had. It is also why the panel must stop selecting key_hash (PR C, BEL-282): with
-- a working UPDATE policy, a browser that can read the column can also overwrite it, so
-- the SELECT exposure and the write capability now compound.
--
-- No grant is added, widened, or narrowed here.
--
-- Dropped before created so a replay does not abort with "policy already exists". Every
-- non-IF-NOT-EXISTS CREATE in this repository is preceded by its drop: see PR #27,
-- weather_admin_delete, and PR #40 section 9.
-- ============================================================
DROP POLICY IF EXISTS "api_keys_owner_update" ON public.api_keys;

CREATE POLICY "api_keys_owner_update"
  ON public.api_keys FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

COMMENT ON POLICY "api_keys_owner_update" ON public.api_keys IS
  'Owner-scoped UPDATE, completing the read/insert/delete set from 20261004123918. Required by handleRerollKey and by the revoked_at write that replaces deletion (BEL-273 PR C). WITH CHECK is what stops an owner reassigning their key row to another user_id. Column scope is not expressible in RLS: an owner may write key_hash, which is the reroll the panel already offers.';

-- ============================================================
-- SECTION 3. Post-check
--
-- Reads the expected state back so the operator is not relying on this file's own
-- success message alone. The owner-scoping assertion is the one that matters: a policy
-- that exists but does not narrow to the caller is worse than no policy, because it
-- looks fixed.
-- ============================================================
DO $$
DECLARE
  policy_def text;
  covers_key_hash boolean;
BEGIN
  SELECT pg_get_expr(pol.polqual, pol.polrelid) || ' / ' || pg_get_expr(pol.polwithcheck, pol.polrelid)
    INTO policy_def
    FROM pg_policy pol
   WHERE pol.polrelid = 'public.api_keys'::regclass
     AND pol.polname = 'api_keys_owner_update';

  IF policy_def IS NULL THEN
    RAISE EXCEPTION 'api_keys_owner_update is absent after this migration ran.';
  END IF;

  covers_key_hash := policy_def LIKE '%auth.uid()%' AND policy_def LIKE '%user_id%';

  IF NOT covers_key_hash THEN
    RAISE EXCEPTION
      'api_keys_owner_update does not reference auth.uid() and user_id in both its USING '
      'and WITH CHECK expressions. It reads: %', policy_def;
  END IF;

  RAISE NOTICE 'api_keys: owner UPDATE policy present and owner-scoped. USING/WITH CHECK: %', policy_def;
  RAISE NOTICE 'api_keys: 4 owner policies now exist (SELECT, INSERT, DELETE, UPDATE).';
END
$$;

-- PostgREST caches the schema and the policy list. Without this reload the panel keeps
-- seeing the pre-migration policy set and the reroll button stays a no-op until the
-- cache expires, which reads as "the migration did not work". Same reason as
-- NOTIFY pgrst, 'reload schema' at the end of both PR #24 migrations.
NOTIFY pgrst, 'reload schema';